### PR TITLE
GitHub Workflows security hardening

### PR DESCRIPTION
**Pull request by sashashura**
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or action) is restricted.
It is recommended to have [most strict permissions on the top level](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) and grant write permissions on [job level](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) case by case.

### CODE REVIEW

**Comment by matttbe** [comment]
Hi @sashashura ,

Thank you for the PR.

The issue we have here is that it is on top of the `export` branch which is overridden when the rest of the tree is modified.
It would be easier if the target branch is `for-review` but even if you do that and because we use TopGit, I will not be able to merge it in `for-review`.

In this special case, the PR has to be done on top of `t/DO-NOT-MERGE-mptcp-add-CI-support` branch.

I can also apply the patches manually, probably easier.

Regarding the patches, the 3 first ones look good to me and the analysis looks good! (just please next time add the useful info from your PR into the git commit: the PR info are attached to Github and might not be available later for some reasons)

Regarding the last patch modifying `notif.yml`, I have a couple of questions:
- why do we need `contents: read`? Is it not only needed to fetch data using an account?
  - `build` is only doing a `curl` command without credentials, no internal GitHub API, should not be needed, does it?
  - `build-error` needs to access some `secrets`, maybe why?
  - `tests`: same as `build-error`
- why do we need `checks: write`? Patchwork is an external service not linked to GitHub and we contact it using `curl`, no internal GitHub API. We access `check` results but also via Curl, without credentials. So it should not be needed, right?

**Comment by sashashura** [comment]
Hi @matttbe,
I see. I have targeted the default branch. It would be nice if you could apply the patches manually where needed.

I think you are right in both cases. I added `contents: read` because wasn't sure about `"${{ env.URI }}/repos/${{ github.repository }}/git/matching-refs/tags/"` and it is quite safe for public repositories, since it is available anyway. But since it doesn't use the token it can work with `permissions: {}` too. I saw the patchwork is external and uses `secrets.PW_TOKEN`, but got confused by the purpose of the step.
All in all I think it is enough to add `permissions: {}` to the notif.yml since it doesn't need special permissions.

**Comment by matttbe** [comment]
>  I see. I have targeted the default branch. It would be nice if you could apply the patches manually where needed.

Sure, I can do that. I'm going to squash them and replace the commit message by what you wrote here.

>  All in all I think it is enough to add `permissions: {}` to the notif.yml since it doesn't need special permissions.

It makes sense, I can do that

**Comment by matttbe** [comment]
Applied in `t/DO-NOT-MERGE-mptcp-add-CI-support` branch, see 6ed3e2a8e162ca1bbd0ed4f9db9b8cbbfc09d2da

The commit has been propagated with TopGit and the modification is now visible in the `export` branch. Thank you for your PR!

**Pull request closed without merging**
